# Generated by Django 3.1.7 on 2021-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR')], max_length=255)),
                ('methylation_analysis', models.BooleanField(default=False)),
                ('copy_number_variation_analysis', models.BooleanField(default=False)),
                ('prefix', models.CharField(default='', max_length=255)),
                ('status_parameter_analysis', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('basecaller', models.CharField(default='', max_length=255)),
                ('megalodon_input_directory', models.CharField(default='', max_length=255)),
                ('megalodon_output_directory', models.CharField(default='', max_length=255)),
                ('megalodon_output_parameters', models.CharField(default='', max_length=255)),
                ('fasta_reference_directory', models.CharField(default='', max_length=255)),
                ('guppy_config', models.CharField(default='', max_length=255)),
                ('guppy_server_path', models.CharField(default='', max_length=255)),
                ('megalodon_devices', models.CharField(default='', max_length=255)),
                ('megalodon_processes', models.CharField(default='', max_length=255)),
                ('megalodon_mod_motif', models.CharField(default='', max_length=255)),
                ('methylationcaller', models.CharField(default='', max_length=255)),
                ('aligner', models.CharField(default='', max_length=255)),
                ('status_parameter_input_directory', models.CharField(default='', max_length=255)),
                ('status_parameter_output_directory', models.CharField(default='', max_length=255)),
                ('cnv_input_directory', models.CharField(default='', max_length=255)),
                ('cnv_output_directory', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('live_processing', models.BooleanField(default=False)),
                ('basecalling', models.BooleanField(default=False)),
                ('methylation_calling', models.BooleanField(default=False)),
                ('alignment', models.BooleanField(default=False)),
                ('fast5_dir', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('processed', models.CharField(choices=[('INITIATED', 'INITIATED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
