# Generated by Django 3.1.7 on 2021-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_analysismodel_experiment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='config_id',
            field=models.IntegerField(default=1),
        ),
    ]
