# Generated by Django 3.1.7 on 2021-03-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_configmodel_guppy_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='megalodon_output_parameters',
        ),
    ]
