# Generated by Django 3.1.7 on 2021-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_remove_configmodel_megalodon_output_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='cnv_output_directory',
        ),
    ]
