# Generated by Django 3.1.7 on 2021-05-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_remove_configmodel_megalodon_mod_motif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configmodel',
            old_name='megalodon_input_directory',
            new_name='megalodon_parameters',
        ),
        migrations.RemoveField(
            model_name='experimentmodel',
            name='description',
        ),
    ]
